FORMAT: 1A

# Guards' Login APIs

Providing HTTP API for guards' client, allowing them to login and logout.

## Login [/guard/login]

### perform login [POST]

+ Request (application/json)

{
    "username": "随千山",
    "password": "asdfghjkl;'"
}

+ Response 200 (application/json)

{
    "status": "ok",
    "jwt_token": "imaweirdo",
    "working_communities":[
        {
            "community_id": 42,
            "community": "同德小区",
            "address": "武汉市江岸区胜利街275号",
        },
        {
            "community_id": 43,
            "community": "其他小区",
            "address": "武汉市江岸区胜利街244号",
        }
    ] 
}

## Logout [/guard/logout]

### perform logout [POST]

+ Response 200

{
    "status": "ok"
}