FORMAT: 1A

# Guards' QR Code APIs

Providing HTTP API for guards' client, allowing them authenticate residents' QR code.

## Validate Access [/guard/validate]

### request a submission [POST]

+ Request (application/json)

{
    "secret": "instapass{YzNWcFkybGtZV2x5WlElM0QlM0Q=}",
    "reason": "压马路"
}

+ Response (application/json)

{
    "status": "ok",
    "validation": "accepted"
}

## Generate QR Code [/guard/generate]

### request a qr code. reason just needed when temporary is true.

+ Request (application/json)

{
    "temporary": false,
    "reason": "临时出入",
    "community_id": 40
}

+ Response (application/json)

{
    "status": "ok",
    "secret": "instapass{?????????????????????}",
    "last_refresh_time": 1593268115,
}