FORMAT: 1A

# Administrators' Notification APIs

Providing HTTP API for administrators' client, allowing them to send or revoke notifications to their responsible communities' guards and residents.

## Post Notification [/admin/notify/release]

### release notification [POST]

+ Request (application/json)

{
    "notification": {
        "community_id": 42,
        "community": "小区10",
        "author": "上海市人民代表大会",
        "address": "上海市人民大道200号",
        "content": "blablablablablabla"
    }
}

+ Response 200 (application/json)

{
    "status": "ok"
}



## Be Notified [/admin/notifications]

### retrieve latest notifications [GET]

+ Response 200 (application/json)

{
    "status": "ok",
    "last_retrieve_time": 1589014399,
    "notifications": [
        {
            "community_id": 42,
            "community": "小区10",
            "author": "上海市人民代表大会",
            "address": "上海市人民大道200号",
            "content": "blablablablablabla"
        },
        {
            "community_id": 43,
            "community": "小区11",
            "author": "北京市人民代表大会",
            "address": "北京市朝阳区建国门南大街6号",
            "content": "zzzzzzzzzzzzzzzzzzzzzzzzz"
        }
    ]
}

