FORMAT: 1A

# Residents' Login APIs

Providing HTTP API for residents' client, allowing them to login and logout.

## Login [/resident/login]

### perform login [POST]

+ Request (application/json)

{
    "username": "随千山",
    "password": "asdfghjkl;'"
}

+ Response 200 (application/json)

{
    "status": "ok",
    "jwt_token": "imaweirdo"
}

## Logout [/resident/logout]

### perform logout [POST]

+ Response 200

{
    "status": "ok"
}