FORMAT: 1A

# Residents' Login APIs

Providing HTTP API for residents' client, allowing them to login and logout.

## Login [/resident/login]

### perform login [POST]

+ Request (application/json)

{
    "real_name": "随*山",
    "id_number": "123123123********123123"
}

+ Response 200 (application/json)

{
    "status": "ok",
    "jwt_token": "imaweirdo"
}

## Logout [/resident/logout]

### perform logout [POST]

+ Response 200

{
    "status": "ok"
}