FORMAT: 1A

# Residents' Profile APIs

Providing HTTP API for residents' client, related to their personal account profile.

## Avatar [/resident/avatar]

### get current avatar [GET]

+ Response 200 (application/json)

{
    "status": "ok",
    "user_name": "随千山",
    "image_uuid": "56c93dce-8887-11ea-bfef-acde48001122",
    "size": {
        "width": 1024,
        "height": 1024
    },
    "format": "png",
    "size": 38869
}

### change avatar [POST]

+ Request (application/json)

{
    "image_uuid": "b2395f72-8887-11ea-bfef-acde48001122"
}

+ Response 200 (application/json)

{
    "status": "ok",
    "size": {
        "width": 1024,
        "height": 1024
    },
    "format": "jpg",
    "size": 57472
}

## View History [/resident/history/{id}]

+ Parameters

    + id: 1 (number) - An unique identifier of the community.

### retrieve history [GET]

+ Response 200 (application/json)
{
    "status": "ok",
    "current_status": "outside/inside",
    "last_exit_time": 1589012733,
    "history": [
        {
            "community_id": 421,
            "community": "同德小区",
            "address": "武汉市江岸区胜利街275号",
            "time": 1589012733,
            "reason": "治病"
        },
        {
            "community_id": 421,
            "community": "同德小区",
            "address": "武汉市江岸区胜利街275号",
            "time": 158901127,
            "reason": "买菜"
        }
    ]
}

## Retrieve Personal Information [/resident/info]

### retrieve info [GET]

+ Response 200 (application/json)

{
    "status": "ok",
    "variable_info": {
        "nickname": "昵称",
        "phone_no": "13912345678",
        "mail_address": "akaza_akari@outlook.com"
    },
    "static_info": {
        "realname": "随*山",
        "id_number": "123123123********123123",
    }
}

### request update info [POST]

+ Request (application/json)

{
    "variable_info": {
        "nickname": "昵称",
        "phone_no": "13912345678",
        "mail_address": "akaza_akari@outlook.com"
    }
}

+ Response 200 (application/json)

{
    "status": "ok"
}

## Upload Image [/resident/upload]

### update image [POST]

+ Request (multipart/form-data)

+ Response 201 (application/json)

{
    "status": "ok",
    "uuid": "56c93dce-8887-11ea-bfef-acde48001122"
}

## Certification [/resident/certification?id_number={id_number}]

+ Parameters

    + id_number: (string) - The number of this user's ID card.

### get current certification [GET]

+ Response 200 (application/json)

{
    "status": "ok",
    "realname": "随*山",
    "id_number": "123123123********123123",
    "id_card_snapshot": "base64_image"
}

## Certificate [/resident/certificate]

### certificate [POST]

+ Request (application/json)

{
    "id_card_snapshot": "base64_image",
}

+ Response 200 (application/json)

{
    "status": "ok",
    "realname": "随*山",
    "id_number": "123123123********123123",
}